### PR TITLE
Google analytics

### PR DESCRIPTION
**Pull request by jessicasalmon**
So far we have google analytics and tag manager set up with some basic examples. Sohil is going to continue setting up the tags once we have a the list of required metrics.

### CODE REVIEW

**Comment by sohilpandya** [comment]
@jessicasalmon, please have a look at the additions I've made and if you are happy I can assign this to Dan. 👍

**Comment by sohilpandya** [comment]
@Danwhy could you please check this branch out and merge if all is OK, I'm not going to be covering the 0.04 % difference.

**Comment by iteles** [comment]
@sohilpandya Please note _why_ you won't be covering the difference.

**Comment by sohilpandya** [comment]
There are 4 files where the coverage has gone down by ~0.01. I am not sure what is causing 3 of those as we are in the error and we've usually been ignoring the error case. 

I'm currently getting some of the other fixes in and once I've had a look I can come back to this depending on time.

**Pull request merged**
