### PR TITLE
Quizreview

### PR DESCRIPTION
**Pull request by sohilpandya**

### CODE REVIEW

**Comment by minaorangina** [comment]
@sohilpandya also still need to make a decision with the ReviewQuiz/QuizReview thing :+1:

**Comment by sohilpandya** [comment]
@minaorangina which one should we go with?

**Comment by sohilpandya** [comment]
@minaorangina I have changed the name of the folder in the front end to review, and it is called quiz-review everywhere else. 

Does that work?

**Comment by minaorangina** [comment]
@sohilpandya not entirely sure. I reckon one can just be called `Review`. On my working branch, I've called the student history component just `History`, because it was obvious from the folder structure. 

Maybe just call the component `Review`, and call everything else `QuizReview`?  ~~`ReviewQuiz~~` doesn't make a great deal of sense. 

And maybe the state should just be called `review` as well. What do you think?

**Comment by sohilpandya** [comment]
@minaorangina OK, we can go with that, I'll make that change now.

**Comment by sohilpandya** [comment]
@minaorangina could you please check, hope i've done it right. 😟

**Pull request merged**
