### PR TITLE
Lecturer restyling

### PR DESCRIPTION
**Pull request by shouston3**
The files changed in the first commit are the ones to review. The others are linting error fixes.

screen shot 2017-02-03 at 14 34 12

### CODE REVIEW

**Comment by sohilpandya** [comment]
Thanks for the update, few things to tackle:
- buttons at the top right need margin between them (currently next to each other)
- line needs to be a secondary colour (not black)
- Quiz and Surveys are taking up full screen, it needs to take up half the screen as in the designs and the right side needs to have Medal Threshold. 
- quiz number comes before the quiz logo 
- no. of questions is a secondary colour (not black). 
- add a new quiz and add a new survey need to be consolidated into one button called `add a new quiz/survey` also needs to be center aligned.

**Comment by sohilpandya** [comment]
@iteles, after discussions with @shouston3, we feel that making this page look like the wireframe means that it's a bit empty on the right side (no trophies and no leaderboard on this page)
screen shot 2017-02-03 at 15 23 02

Hence I suggested going down the max-width route so that the content doesn't look stretched out (54rems - like some other pages)

Please let us know your thoughts. 

Thanks

**Comment by shouston3** [comment]
Implemented some of the quick things you've mentioned.
If we consolidate the "Add A New Quiz" and "Add a New Survey" buttons into one button, then how should we break up the divide between quizzes and surveys?

**Comment by shouston3** [comment]
New View after implementing quick wins:

screen shot 2017-02-03 at 15 49 00

**Comment by iteles** [comment]
@shouston3 Didn't each of those sections used to have a title? i.e 'Quizzes' and 'Surveys'?
That's how we differentiate.

You also need more whitespace between the medals and the other sections, looking a little bunched up.

**Comment by shouston3** [comment]
Now the view:

screen shot 2017-02-03 at 17 12 12

**Comment by sohilpandya** [comment]
@shouston3 final change related to the quiz icon coming after the quiz/survey number.

**Comment by shouston3** [comment]
Great, just that to go. It's proving quite a bit trickier than I previously though

**Comment by sohilpandya** [comment]
@shouston3 👍 Nearly done though! looking forward to seeing the final result! 😄

**Comment by shouston3** [comment]
Right, I hope that's everything:

screen shot 2017-02-03 at 17 42 45

**Comment by sohilpandya** [comment]
@shouston3 sorry but one final thing before I review the code - line colour needs to change to the secondary one.

**Comment by shouston3** [comment]
@sohilpandya Changed the colour

**Comment by sohilpandya** [comment]
Had a look through the code, lots of bits have been taken out, but looks like that was all the linting issues. 

CSS looks good! Great job on it!

**Pull request merged**
