### PR TITLE
free plan

### PR DESCRIPTION
**Pull request by sohilpandya**
- made the lectuer login public
- added trial field in table
- create a timestamp when a lecturer registers
 submitting trial information when user signs up ( if existing user tries logging in, they will be able to do so)
- check if the trial is valid
- if user is already signed in and the trial expires we log user out. When they try login in again, they get same message as above.

related to #621

### CODE REVIEW

**Comment by sohilpandya** [comment]
@Danwhy we need some help, for some reason it is not covering this line https://codecov.io/gh/cul-2016/quiz/compare/c32f445f36c37ecc2315c656cd25f8bb0ffff94d...b3325de3b03112479baa60c80c0c62565b872d2b/src/server/plugins/strategy.js#L10

We are definitely doing tests on it here https://github.com/cul-2016/quiz/pull/632/commits/f0f640b37493ea4e419890630ce7f7017c40eb42

Any ideas what could cause this line to not be covered. I've put a console log inside that block and it is definitely getting inside that block when running the test. :(

**Comment by sohilpandya** [comment]
Otherwise this PR is ready 😢

**Comment by sohilpandya** [comment]
@Danwhy we thought we'd fixed it in #633 but luck still, I'd rather you look at that version as we've worked on the test a little more. 

Still for some reason it gets in the if statement but doesnt run the callback.

**Comment by Danwhy** [comment]
@sohilpandya As far as I can see, on this branch, the token is invalid, that's why it's returning a 401 and the test is passing. 

In the changes you've made in #633, the user is not getting logged in at all because the trial has expired, so again that clause isn't being called.

It's quite a difficult condition to test, the only thing I can think to suggest is to log the user in with a valid trial time, then maybe mock the `Date.now` function to return a date in the future where the trial will have expired.

I'll merge this branch for now, we can look at fixing this in a future pr

**Pull request merged**
