### PR TITLE
Final small edits

### PR DESCRIPTION
**Pull request by sohilpandya**
Updated all the small edits found in #460, in addition to that I've updated the css issue that was found in #444.

I have also tested both #439 & #402. They seem to be working fine locally, It could be the case that the changes for this have not been pushed to master? They are only present on the staging version of the app? **As they seem to be working ok on the staging version of the app as well**

Could we get this PR merged into master and pushed to the live app, we can then test those two out again and see if the issue still persists.

### CODE REVIEW

**Comment by stianr** [comment]
(Not sure whether I was meant to approve there - sorry if I wasn't meant to.)

**Comment by sohilpandya** [comment]
@iteles we have automatic deployment for the master branch, so the changes went live when you merged the PR in. 

Would you like me to disable this feature from Heroku?

**Comment by iteles** [comment]
@sohilpandya Not at all, would be good to add a line to the docs and make master a protected branch (that you can't push to directly) though :+1:

**Comment by sohilpandya** [comment]
That's all done.

**Pull request merged**
